### ISSUE TITLE
Facebook crossposting

### ISSUE THREAD

**Issue by PouleR** [Martin1982/live-broadcast-bundle#58]
Add an option to crosspost Facebook live video's. (https://developers.facebook.com/docs/graph-api/video-uploads#crosspostedvideos).

This is based on the video id and can only be executed when crossposting is enabled for video's, which can be enabled after creating a live video.

**Comment by Martin1982** [comment]
This feature is a little niche for the moment, closing for now. Can be reopened with extra argumentation as to why this is required.
