### ISSUE TITLE
Scheduler blocks after starting a broadcast

### ISSUE THREAD

**Issue by PouleR** [Martin1982/live-broadcast-bundle#71]
Introduced in v0.6; the scheduler blocks after starting a broadcast. For e.g. this command is executed:

`(ffmpeg -stream_loop -1 -re -i '<URL>' -c:v libx264 -crf 30 -preset ultrafast -c:a copy -f flv "rtmp://live-api.facebook.com:80/rtmp/<KEY>" -metadata broadcast_id=22 -metadata channel_id=1 -metadata env=dev >/var/logs/livebroadcaster-ffmpeg-2018-02-19_113150.log 2>&1/app/../bin/console livebroadcaster:broadcast:end 22 1) &`

The command is not started in the background since the end command is added, this affects the behaviour of the scheduler. Broadcasts are not stopped anymore and new broadcasts can not be started.

**Comment by Martin1982** [comment]
This has been solved in 0.7.0
