### ISSUE TITLE
YouTube thumbnails not updated onUpdate

### ISSUE THREAD

**Issue by PouleR** [Martin1982/live-broadcast-bundle#72]
When a YouTube broadcast is updated, the thumbnail is not taken into account. Since the thumbnail property of the live broadcast is a string (not a File) the new thumbnail is ignored.

Proposal to:
- Remove the YouTubeConfig class and create a new ThumbnailService
- This service returns a (new) Thumbnail entity that can be used by other channels, with these properties:
-- width
-- height
-- url
-- filelocation (path)
-- filename

**Comment by Martin1982** [comment]
Is this still the case in 0.7.0 @PouleR ?

**Comment by Martin1982** [comment]
Fixed in 31673a935d4a291f19ab53517e42e1f7f22dac5c
