### ISSUE TITLE
YouTube thumbnails

### ISSUE THREAD

**Issue by PouleR** [Martin1982/live-broadcast-bundle#77]
YouTube thumbnails can't be included in the LiveBroadcast Resource onInsert and onUpdate since the property won't be updated:

https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/insert

To fix this the YouTube Data API should be used together with the videoId: https://developers.google.com/youtube/v3/code_samples/php#upload_a_custom_video_thumbnail_image

**Comment by PouleR** [comment]
@Martin1982 I think this issue can be closed?

**Comment by Martin1982** [comment]
This is true for adding thumbnails upon creation, when updating an item it's not being replaced on the remote channel

**Comment by Martin1982** [comment]
#72 describes updating, hence closing the issue
