### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by PouleR** [Martin1982/live-broadcast-bundle#90]
Fix deprecations:

`User Deprecated: The "live.broadcast.facebookapi.service" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`

**Comment by Martin1982** [comment]
This error is not occurring in the current version, hence closing the issue. If this error is still present please provide a way to reproduce.
